### ISSUE TITLE
Buttons Not Working

### ISSUE THREAD

**Issue by LoadedReaperFN** [ModernKit/xcloud-keyboard-mouse#1]
### Bug description

When I click a button, it doesn't work for me. Normally the extension should lead me to extensionpay.com but instead, it does nothing. Please fix this asap because I have a fortnite tournament to play today and I can't miss it!

### Extension Version

3.5

### What browser(s) are you seeing the problem on?

Chrome

**Comment by idolize** [comment]
Hi - there was a brief issue where the trial and payment links weren't working but it should be resolved now. Are you still having this issue?

**Comment by ModernKit** [comment]
Hi @LoadedReaperFN, please let us know if you're still facing this issue by reopening this issue or emailing us at support@modernkit.one
